sudo: false
language: java
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
    - oracle-java8-installer
after_success:
  - mvn jacoco:report coveralls:report
  - mvn deploy -DskipTests=true --settings settings.xml
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f34d68708d0b9bd6b567
    on_success: change
    on_failure: always
    on_start: false
